services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend

  frontend:
    build: .
    environment: 
      - FOO=BAR
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  

  mongo:
    image: mongo